package media

import (
	"bytes"
	"encoding/binary"
	"hash/crc32"
	"image"
	"image/color"
	"image/jpeg"
	"image/png"
	"testing"

	"github.com/juriku/untrace/internal/provenance"
)

func basePNG(t *testing.T) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, 2, 2))
	img.Set(0, 0, color.RGBA{R: 255, A: 255})
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func baseJPEG(t *testing.T) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, 8, 8))
	var buf bytes.Buffer
	if err := jpeg.Encode(&buf, img, nil); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// insertPNGChunk places a chunk immediately before IEND, where ancillary chunks
// legally live.
func insertPNGChunk(t *testing.T, data []byte, typ string, payload []byte) []byte {
	t.Helper()
	iend := bytes.LastIndex(data, []byte("IEND"))
	if iend < 4 {
		t.Fatal("no IEND in fixture")
	}
	at := iend - 4

	chunk := make([]byte, 0, len(payload)+12)
	chunk = binary.BigEndian.AppendUint32(chunk, uint32(len(payload)))
	chunk = append(chunk, typ...)
	chunk = append(chunk, payload...)
	chunk = binary.BigEndian.AppendUint32(chunk, crc32.ChecksumIEEE(append([]byte(typ), payload...)))

	out := make([]byte, 0, len(data)+len(chunk))
	out = append(out, data[:at]...)
	out = append(out, chunk...)
	return append(out, data[at:]...)
}

// insertJPEGSegment places a segment straight after SOI.
func insertJPEGSegment(t *testing.T, data []byte, marker byte, payload []byte) []byte {
	t.Helper()
	seg := []byte{0xFF, marker}
	seg = binary.BigEndian.AppendUint16(seg, uint16(len(payload)+2))
	seg = append(seg, payload...)

	out := make([]byte, 0, len(data)+len(seg))
	out = append(out, data[:2]...)
	out = append(out, seg...)
	return append(out, data[2:]...)
}

func kindsOf(r Report) map[Kind]bool {
	out := map[Kind]bool{}
	for _, f := range r.Findings {
		out[f.Kind] = true
	}
	return out
}

func onlyKind(k Kind) func(Finding) bool {
	return func(f Finding) bool { return f.Kind == k }
}

func everyRecord(Finding) bool { return true }

func TestDetectFormats(t *testing.T) {
	if got := Detect(basePNG(t)); got != FormatPNG {
		t.Errorf("png detected as %q", got)
	}
	if got := Detect(baseJPEG(t)); got != FormatJPEG {
		t.Errorf("jpeg detected as %q", got)
	}
	if got := Detect([]byte("just text")); got != FormatUnknown {
		t.Errorf("text detected as %q", got)
	}
}

func TestCleanImageHasNoFindings(t *testing.T) {
	for name, data := range map[string][]byte{"png": basePNG(t), "jpeg": baseJPEG(t)} {
		if r := Inspect(data); len(r.Findings) != 0 {
			t.Errorf("%s: clean image reported %+v", name, r.Findings)
		}
	}
}

func TestPNGC2PADetectedAndStripped(t *testing.T) {
	data := insertPNGChunk(t, basePNG(t), "caBX", []byte("jumbc2pa manifest store"))

	if !kindsOf(Inspect(data))[C2PA] {
		t.Fatal("caBX chunk not reported as C2PA")
	}

	out, changed, err := Strip(data, onlyKind(C2PA))
	if err != nil || !changed {
		t.Fatalf("Strip: changed=%v err=%v", changed, err)
	}
	if kindsOf(Inspect(out))[C2PA] {
		t.Error("C2PA still present after strip")
	}

	// The point of stripping metadata is that the image survives it.
	if _, err := png.Decode(bytes.NewReader(out)); err != nil {
		t.Errorf("stripped png no longer decodes: %v", err)
	}
}

func TestPNGTextChunkReportsKeywordAndValue(t *testing.T) {
	payload := append([]byte("Software"), 0)
	payload = append(payload, []byte("Some Image Generator 1.0")...)
	data := insertPNGChunk(t, basePNG(t), "tEXt", payload)

	r := Inspect(data)
	if len(r.Findings) != 1 {
		t.Fatalf("got %d findings, want 1", len(r.Findings))
	}
	f := r.Findings[0]
	if f.Kind != PNGText || f.Label != "Software" || f.Value != "Some Image Generator 1.0" {
		t.Errorf("got %+v", f)
	}
}

func TestPNGStripLeavesOtherChunks(t *testing.T) {
	data := insertPNGChunk(t, basePNG(t), "caBX", []byte("c2pa"))
	data = insertPNGChunk(t, data, "tEXt", append([]byte("Author"), 0))

	out, _, err := Strip(data, onlyKind(C2PA))
	if err != nil {
		t.Fatal(err)
	}
	if !kindsOf(Inspect(out))[PNGText] {
		t.Error("stripping C2PA also removed the text chunk")
	}
}

func TestJPEGC2PADetectedAndStripped(t *testing.T) {
	data := insertJPEGSegment(t, baseJPEG(t), 0xEB, []byte("\x00\x00jumbc2pa manifest"))

	if !kindsOf(Inspect(data))[C2PA] {
		t.Fatal("APP11 segment not reported as C2PA")
	}

	out, changed, err := Strip(data, onlyKind(C2PA))
	if err != nil || !changed {
		t.Fatalf("Strip: changed=%v err=%v", changed, err)
	}
	if kindsOf(Inspect(out))[C2PA] {
		t.Error("C2PA still present after strip")
	}
	if _, err := jpeg.Decode(bytes.NewReader(out)); err != nil {
		t.Errorf("stripped jpeg no longer decodes: %v", err)
	}
}

func TestJPEGCommentReported(t *testing.T) {
	data := insertJPEGSegment(t, baseJPEG(t), 0xFE, []byte("generated by a model"))
	r := Inspect(data)
	if len(r.Findings) != 1 || r.Findings[0].Kind != JPEGComment {
		t.Fatalf("got %+v", r.Findings)
	}
	if r.Findings[0].Value != "generated by a model" {
		t.Errorf("value = %q", r.Findings[0].Value)
	}
}

func TestJPEGExifSoftwareExtracted(t *testing.T) {
	data := insertJPEGSegment(t, baseJPEG(t), 0xE1, exifWithSoftware("Firefly 3"))

	r := Inspect(data)
	if len(r.Findings) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(r.Findings), r.Findings)
	}
	f := r.Findings[0]
	if f.Kind != EXIF || f.Label != "Software" || f.Value != "Firefly 3" {
		t.Errorf("got %+v", f)
	}
}

func TestXMPCreatorToolExtracted(t *testing.T) {
	xmp := append([]byte(nil), xmpNamespace...)
	xmp = append(xmp, []byte(`<x><xmp:CreatorTool>Some Model</xmp:CreatorTool></x>`)...)
	data := insertJPEGSegment(t, baseJPEG(t), 0xE1, xmp)

	r := Inspect(data)
	if len(r.Findings) != 1 || r.Findings[0].Kind != XMP {
		t.Fatalf("got %+v", r.Findings)
	}
	if r.Findings[0].Value != "Some Model" {
		t.Errorf("CreatorTool = %q", r.Findings[0].Value)
	}
}

func TestStripOnlyRequestedKinds(t *testing.T) {
	data := insertJPEGSegment(t, baseJPEG(t), 0xFE, []byte("a comment"))
	data = insertJPEGSegment(t, data, 0xEB, []byte("jumbc2pa"))

	out, _, err := Strip(data, onlyKind(C2PA))
	if err != nil {
		t.Fatal(err)
	}
	got := kindsOf(Inspect(out))
	if got[C2PA] {
		t.Error("C2PA survived")
	}
	if !got[JPEGComment] {
		t.Error("comment was removed but was not requested")
	}
}

func TestStripSelectsRecordsNotKinds(t *testing.T) {
	data := insertPNGChunk(t, basePNG(t), "tEXt", []byte("Software\x00Adobe Firefly 3"))
	data = insertPNGChunk(t, data, "tEXt", []byte("Author\x00Jane Roe"))

	out, changed, err := Strip(data, func(f Finding) bool {
		return bytes.Contains([]byte(f.Value), []byte("Firefly"))
	})
	if err != nil || !changed {
		t.Fatalf("Strip: changed=%v err=%v", changed, err)
	}

	var survivors []Finding
	for _, f := range Inspect(out).Findings {
		if f.Kind == PNGText {
			survivors = append(survivors, f)
		}
	}
	if len(survivors) != 1 {
		t.Fatalf("got %d text chunks, want 1: %+v", len(survivors), survivors)
	}
	if survivors[0].Label != "Author" {
		t.Errorf("kept %q, want the record naming no generator", survivors[0].Label)
	}
}

func TestStripNonImageIsANoop(t *testing.T) {
	in := []byte("plain text file")
	out, changed, err := Strip(in, onlyKind(C2PA))
	if err != nil || changed || !bytes.Equal(in, out) {
		t.Errorf("changed=%v err=%v out=%q", changed, err, out)
	}
}

func TestManifestNamesItsGenerator(t *testing.T) {
	manifest := append([]byte("jumbc2pa\x00\x01claim_generator"), 0x71)
	manifest = append(manifest, "Claude 3.5 Sonnet"...)
	data := insertPNGChunk(t, basePNG(t), "caBX", manifest)

	var got Finding
	for _, f := range Inspect(data).Findings {
		if f.Kind == C2PA {
			got = f
		}
	}
	if got.Value != "claude" {
		t.Errorf("value = %q, want the generator it names", got.Value)
	}
	if _, ok := provenance.Generator(got.Value); !ok {
		t.Error("the reported value does not name a generator")
	}
}

func TestCameraManifestNamesNoGenerator(t *testing.T) {
	manifest := []byte("jumbc2pa\x00\x01claim_generator\x71Leica Camera AG M11")
	data := insertPNGChunk(t, basePNG(t), "caBX", manifest)

	for _, f := range Inspect(data).Findings {
		if f.Kind != C2PA {
			continue
		}
		if _, ok := provenance.Generator(f.Value); ok {
			t.Errorf("camera manifest reported as AI: %q", f.Value)
		}
	}
}

// Generator strips non-alphanumerics, so bytes that spell a name only once the
// gaps are removed must not match.
func TestScatteredBytesDoNotSpliceIntoAGenerator(t *testing.T) {
	manifest := []byte("c\x00l\x00a\x00u\x00d\x00e\x00")
	data := insertPNGChunk(t, basePNG(t), "caBX", manifest)

	for _, f := range Inspect(data).Findings {
		if f.Kind == C2PA && f.Value != "" {
			t.Errorf("scattered bytes matched: %q", f.Value)
		}
	}
}

func TestStripPNGPreservesTrailingBytes(t *testing.T) {
	trailer := []byte("TRAILING-DATA")
	data := insertPNGChunk(t, basePNG(t), "caBX", []byte("jumbc2pa manifest"))
	data = append(data, trailer...)

	out, changed, err := Strip(data, onlyKind(C2PA))
	if err != nil || !changed {
		t.Fatalf("Strip: changed=%v err=%v", changed, err)
	}
	if kindsOf(Inspect(out))[C2PA] {
		t.Error("C2PA survived the strip")
	}
	if !bytes.HasSuffix(out, trailer) {
		t.Errorf("trailing bytes dropped: out ends %q", out[max(0, len(out)-len(trailer)):])
	}
}

func TestTruncatedFilesDoNotPanic(t *testing.T) {
	for _, data := range [][]byte{
		basePNG(t)[:20],
		baseJPEG(t)[:6],
		append(append([]byte(nil), pngSignature...), 0xFF, 0xFF, 0xFF, 0xFF),
	} {
		Inspect(data)
		if _, _, err := Strip(data, onlyKind(C2PA)); err == nil {
			continue
		}
	}
}

// exifWithSoftware builds a minimal little-endian TIFF block with one IFD entry
// holding tag 0x0131.
func exifWithSoftware(value string) []byte {
	v := append([]byte(value), 0)

	body := append([]byte(nil), exifHeader...)
	tiff := []byte{'I', 'I', 42, 0, 8, 0, 0, 0}
	tiff = binary.LittleEndian.AppendUint16(tiff, 1) // one entry

	entry := make([]byte, 0, 12)
	entry = binary.LittleEndian.AppendUint16(entry, 0x0131)
	entry = binary.LittleEndian.AppendUint16(entry, 2) // ASCII
	entry = binary.LittleEndian.AppendUint32(entry, uint32(len(v)))
	// Values longer than four bytes live at an offset from the TIFF header.
	entry = binary.LittleEndian.AppendUint32(entry, uint32(len(tiff)+12+4))

	tiff = append(tiff, entry...)
	tiff = binary.LittleEndian.AppendUint32(tiff, 0) // no next IFD
	tiff = append(tiff, v...)

	return append(body, tiff...)
}
